export const products = [
    {
        id: 1,
        name: 'nombre 1',
        stock: 11,
        price: 11111,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 2,
        name: 'nombre 2',
        stock: 12,
        price: 12222,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 3,
        name: 'nombre 3',
        stock: 13,
        price: 13333,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 4,
        name: 'nombre 4',
        stock: 14,
        price: 14444,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 5,
        name: 'nombre 5',
        stock: 15,
        price: 15555,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 6,
        name: 'nombre 6',
        stock: 16,
        price: 16666,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 7,
        name: 'nombre 7',
        stock: 17,
        price: 17777,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    },
    {
        id: 8,
        name: 'nombre 8',
        stock: 18,
        price: 18888,
        description: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de ',
        image: 'https://www.pngmart.com/files/7/Sneakers-PNG-Picture.png',
    }
]